name: googletest macos

on: push

jobs:
  googletest_macos:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: get cmake
        uses: lukka/get-cmake@latest

      - name: build and run tests
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DMETATEST=ON -DGTEST=ON -DNPL_RELEASE=ON && cmake --build . && ./tests/gtest_rq
